### ISSUE TITLE
WavLM Base+ over Large?

### ISSUE THREAD

**Issue by Pathos0925** [bshall/knn-vc#10]
First, thanks for the paper and the code, this is very interesting!
Did you happen to do any testing with other versions of WavLM, such as Base or Base+? I was wondering if it would be possible to make this lighter without impacting the quality too much.

**Comment by bshall** [comment]
Hi @Pathos0925, thanks for the feedback!

Initially we used HuBERT-Base as the feature extractor. It also works well, maybe slightly worse than WavLM but not by much. I'm not sure if that's due to size or to the training procedure though. We haven't experimented with WavLM-Base or Base+, but I'm confident that they'll work as well. If you do experiment with a smaller model we'd be interested, so please share your results!
