### ISSUE TITLE
Some questions about implementation

### ISSUE THREAD

**Issue by TOGA101** [bshall/knn-vc#31]
1. Since the structure of the LibriSpeech dataset is root/subset/speaker/chapter/file, should https://github.com/bshall/knn-vc/blob/7b59579524f9fdbfe5e92952b7bec70b6253e084/prematch_dataset.py#L57 be modified to `uttrs_from_same_spk = sorted(list(path.parent.parent.rglob('**/*.flac')))`to return other utterances of the same speaker?
2. Since matching and synthesis do not necessarily use the same features, can I use ASR features (like from [Whisper](https://github.com/openai/whisper)) for matching and its corresponding original Mel spectrogram for synthesis?

**Comment by bshall** [comment]
Hi @TOGA101, thanks for the questions.

1. Yes, you are correct that looks like a bug. Although, it might actually help a bit since prematching is done with less reference data and the style might be more consistent within a chapter. I don't think it'll make too much difference in practice though. If you want to submit a PR with the fix I'd be happy to merge it or I can do it at some point?
2. You can match and synthesize on different features. I have tried matching on WavLM features and synthesizing on spectrogram frames. It works, but it seems to cause more boundary artefacts than with the WavLM features. I haven't experimented with Whisper features but I imagine it'll work as well. If you try any of these ideas it'd be great to hear your results.

**Comment by TOGA101** [comment]
OK, thanks.

**Comment by TOGA101** [comment]
I tried retraining HIFIGAN with other features, using your latest provided code using persist workers and simply modifying "hubert_dim" in the config file to match the new feature dimensions, leaving the rest unchanged. I use a single RTX 4090 for training, and the speed is about 0.5 sec/batch and 3000 sec/epoch. It is roughly estimated that it will take about 2 months to complete the training. You mentioned in #9 "The training time for training on train-100 data from librispeech took around a week or two on 3x Quadro RTX 6000 GPUs". Then, the training time on a single RTX 6000 should be about 1 month. As we all know, 4090 has much higher performance than 6000, but the training time is twice as long. I think this must be abnormal. Did I do something wrong? Can you give me some advice? Thank you very much.
